// PDF Export using browser print — supports Arabic natively via web fonts

const getCurrentLang = () => localStorage.getItem('tatabu_lang') || 'ar';

const L = {
  ar: {
    appName: 'تَتَبُعْ',
    appSub: 'إدارة الحلقات القرآنية',
    student: 'الطالب',
    class: 'الحلقة',
    period: 'الفترة',
    total: 'الإجمالي',
    present: 'حاضر',
    absent: 'غائب',
    rate: 'نسبة الحضور',
    date: 'التاريخ',
    hijriDate: 'التاريخ الهجري',
    surah: 'السورة',
    ayahs: 'الآيات',
    evaluation: 'التقييم',
    status: 'الحالة',
    hizb: 'حزب',
    totalHizb: 'إجمالي الحزب',
    teacher: 'المعلم',
    school: 'المدرسة',
    rank: 'الترتيب',
    attendance: 'ملخص الحضور',
    progress: 'تقدم الحفظ',
    notes: 'ملاحظات المعلم',
    name: 'الاسم',
    students: 'الطلاب',
    classPerf: 'أداء الحلقات',
    studentRank: 'ترتيب الطلاب',
    generatedBy: 'صُنع بواسطة تَتَبُعْ',
    attendReport: 'تقرير الحضور',
    memoReport: 'تقرير التسميع',
    progressReport: 'تقرير التقدم',
    schoolReport: 'تقرير المدرسة',
    eval_excellent: 'ممتاز',
    eval_good: 'جيد',
    eval_average: 'متوسط',
    eval_repeat: 'إعادة',
  },
  en: {
    appName: 'Tatabu',
    appSub: 'Quranic School Management',
    student: 'Student',
    class: 'Class',
    period: 'Period',
    total: 'Total Sessions',
    present: 'Present',
    absent: 'Absent',
    rate: 'Attendance Rate',
    date: 'Date',
    hijriDate: 'Hijri Date',
    surah: 'Surah',
    ayahs: 'Ayahs',
    evaluation: 'Evaluation',
    status: 'Status',
    hizb: 'Hizb',
    totalHizb: 'Total Hizb',
    teacher: 'Teacher',
    school: 'School',
    rank: 'Rank',
    attendance: 'Attendance Summary',
    progress: 'Memorization Progress',
    notes: "Teacher's Notes",
    name: 'Name',
    students: 'Students',
    classPerf: 'Class Performance',
    studentRank: 'Student Rankings',
    generatedBy: 'Generated by Tatabu',
    attendReport: 'Attendance Report',
    memoReport: 'Memorization Report',
    progressReport: 'Progress Report',
    schoolReport: 'School Report',
    eval_excellent: 'Excellent',
    eval_good: 'Good',
    eval_average: 'Average',
    eval_repeat: 'Repeat',
  },
};

const getStyles = (isAr) => `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: ${isAr ? "'Amiri', 'Scheherazade New', serif" : "'Inter', 'Helvetica Neue', Arial, sans-serif"};
    color: #1e293b;
    background: #fff;
    font-size: ${isAr ? '14px' : '13px'};
    line-height: 1.65;
    direction: ${isAr ? 'rtl' : 'ltr'};
  }
  .page { padding: 24px 30px; max-width: 800px; margin: 0 auto; }

  /* ── Header ── */
  .header {
    background: linear-gradient(135deg, #16a34a 0%, #166534 100%);
    color: #fff;
    padding: 16px 22px;
    border-radius: 10px 10px 0 0;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  .header-brand .name { font-size: 20px; font-weight: 700; }
  .header-brand .sub { font-size: 11px; opacity: 0.8; margin-top: 2px; }
  .header-report { text-align: ${isAr ? 'left' : 'right'}; }
  .header-report .title { font-size: 15px; font-weight: 700; }
  .gold-bar { height: 4px; background: linear-gradient(90deg, #f59e0b, #fbbf24); border-radius: 0 0 6px 6px; margin-bottom: 20px; }

  /* ── Info box ── */
  .info-box {
    background: #f0fdf4;
    border: 1px solid #bbf7d0;
    border-radius: 10px;
    padding: 14px 18px;
    margin-bottom: 18px;
  }
  .info-box .main-name { font-size: 17px; font-weight: 700; color: #15803d; margin-bottom: 5px; }
  .info-box .meta { font-size: 12px; color: #64748b; line-height: 1.7; }

  /* ── Stats ── */
  .stats-row { display: flex; gap: 10px; margin-bottom: 18px; }
  .stat-card {
    flex: 1;
    border-radius: 10px;
    padding: 12px 10px;
    text-align: center;
    color: #fff;
  }
  .stat-card .sv { font-size: 24px; font-weight: 700; }
  .stat-card .sl { font-size: 10px; opacity: 0.85; margin-top: 3px; text-transform: uppercase; letter-spacing: 0.3px; }
  .sc-blue   { background: #2563eb; }
  .sc-green  { background: #16a34a; }
  .sc-red    { background: #dc2626; }
  .sc-gold   { background: #d97706; }

  /* ── Section ── */
  .section { margin-bottom: 20px; }
  .section-header {
    font-size: 13px; font-weight: 700; color: #15803d;
    margin-bottom: 10px; padding-bottom: 6px;
    border-bottom: 2px solid #bbf7d0;
    display: flex; align-items: center; gap: 6px;
  }
  .section-header::before { content: ''; display: inline-block; width: 4px; height: 16px; background: #16a34a; border-radius: 2px; }

  /* ── Table ── */
  table { width: 100%; border-collapse: collapse; }
  th {
    background: #16a34a;
    color: #fff;
    padding: 9px 12px;
    font-size: 11px;
    font-weight: 600;
    text-align: ${isAr ? 'right' : 'left'};
    white-space: nowrap;
  }
  td {
    padding: 8px 12px;
    font-size: 12px;
    border-bottom: 1px solid #f1f5f9;
    text-align: ${isAr ? 'right' : 'left'};
    vertical-align: middle;
  }
  tr:nth-child(even) td { background: #f8fafc; }

  /* ── Badges ── */
  .badge {
    display: inline-block;
    padding: 2px 9px;
    border-radius: 99px;
    font-size: 11px;
    font-weight: 600;
    white-space: nowrap;
  }
  .bg { background: #dcfce7; color: #15803d; }
  .br { background: #fee2e2; color: #b91c1c; }
  .bb { background: #dbeafe; color: #1d4ed8; }
  .bo { background: #fef3c7; color: #92400e; }
  .bp { background: #f3e8ff; color: #6b21a8; }

  /* ── Progress ── */
  .prog-track { background: #e2e8f0; border-radius: 999px; height: 8px; overflow: hidden; flex: 1; }
  .prog-fill  { background: linear-gradient(90deg, #16a34a, #22c55e); height: 100%; border-radius: 999px; }
  .prog-wrap  { display: flex; align-items: center; gap: 8px; }

  /* ── Hizb highlight ── */
  .hizb-box {
    background: #fffbeb;
    border: 1px solid #fde68a;
    border-radius: 10px;
    padding: 14px 18px;
  }
  .hizb-box .hv { font-size: 30px; font-weight: 700; color: #b45309; }
  .hizb-box .hl { font-size: 12px; color: #92400e; margin-top: 2px; }

  /* ── Notes ── */
  .notes-box {
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 10px;
    padding: 14px 18px;
    font-size: 13px;
    color: #475569;
    line-height: 1.8;
    white-space: pre-wrap;
  }

  /* ── Footer ── */
  .footer {
    margin-top: 22px;
    padding-top: 12px;
    border-top: 1px solid #e2e8f0;
    display: flex;
    justify-content: space-between;
    font-size: 11px;
    color: #94a3b8;
  }

  @media print {
    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .header, .stat-card, th { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    @page { margin: 12mm; }
  }
`;

const openPrintWindow = (bodyHtml, reportTitle, lang) => {
  const isAr = lang === 'ar';
  const labels = L[lang] || L.en;
  const today = new Date().toLocaleDateString(isAr ? 'ar-SA-u-ca-islamic' : 'en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const html = `<!DOCTYPE html>
<html dir="${isAr ? 'rtl' : 'ltr'}" lang="${lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${reportTitle}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Amiri:ital,wght@0,400;0,700;1,400&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <style>${getStyles(isAr)}</style>
</head>
<body>
<div class="page">
  <div class="header">
    <div class="header-brand">
      <div class="name">${labels.appName}</div>
      <div class="sub">${labels.appSub}</div>
    </div>
    <div class="header-report">
      <div class="title">${reportTitle}</div>
    </div>
  </div>
  <div class="gold-bar"></div>
  ${bodyHtml}
  <div class="footer">
    <span>${labels.generatedBy}</span>
    <span>${today}</span>
  </div>
</div>
<script>
  document.fonts.ready.then(function() {
    setTimeout(function() { window.print(); }, 400);
  });
</script>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) {
    alert(lang === 'ar' ? 'يرجى السماح بالنوافذ المنبثقة لتصدير التقارير' : 'Please allow pop-ups to export reports');
    return;
  }
  win.document.write(html);
  win.document.close();
};

const evalBadge = (evaluation, lang) => {
  const labels = L[lang] || L.en;
  const cls = { excellent: 'bg', good: 'bb', average: 'bo', repeat: 'br' };
  const text = labels[`eval_${evaluation}`] || evaluation;
  return `<span class="badge ${cls[evaluation] || 'bb'}">${text}</span>`;
};

// ─────────────────────────────────────────────
export const exportAttendancePDF = ({ title, studentName, classN, period, records, stats, lang: langProp }) => {
  const lang = langProp || getCurrentLang();
  const labels = L[lang] || L.en;

  const body = `
    ${studentName ? `
    <div class="info-box">
      <div class="main-name">${studentName}</div>
      <div class="meta">${labels.class}: ${classN || '—'} &nbsp;|&nbsp; ${labels.period}: ${period || '—'}</div>
    </div>` : ''}

    ${stats ? `
    <div class="stats-row">
      <div class="stat-card sc-blue">
        <div class="sv">${stats.total}</div>
        <div class="sl">${labels.total}</div>
      </div>
      <div class="stat-card sc-green">
        <div class="sv">${stats.present}</div>
        <div class="sl">${labels.present}</div>
      </div>
      <div class="stat-card sc-red">
        <div class="sv">${stats.absent}</div>
        <div class="sl">${labels.absent}</div>
      </div>
      <div class="stat-card ${stats.rate >= 80 ? 'sc-green' : 'sc-gold'}">
        <div class="sv">${stats.rate}%</div>
        <div class="sl">${labels.rate}</div>
      </div>
    </div>` : ''}

    <div class="section">
      <div class="section-header">${labels.attendReport}</div>
      <table>
        <thead>
          <tr>
            <th>${labels.date}</th>
            <th>${labels.name}</th>
            <th>${labels.status}</th>
          </tr>
        </thead>
        <tbody>
          ${(records || []).map(r => `
          <tr>
            <td>${r.date}</td>
            <td>${r.studentName || studentName || '—'}</td>
            <td>
              <span class="badge ${r.status === 'present' ? 'bg' : 'br'}">
                ${r.status === 'present' ? labels.present : labels.absent}
              </span>
            </td>
          </tr>`).join('')}
        </tbody>
      </table>
    </div>
  `;

  openPrintWindow(body, title || labels.attendReport, lang);
};

// ─────────────────────────────────────────────
export const exportMemorizationPDF = ({ title, studentName, classN, records, totalHizb, lang: langProp }) => {
  const lang = langProp || getCurrentLang();
  const labels = L[lang] || L.en;
  const isAr = lang === 'ar';

  const body = `
    ${studentName ? `
    <div class="info-box">
      <div class="main-name">${studentName}</div>
      <div class="meta">
        ${labels.class}: ${classN || '—'}
        &nbsp;|&nbsp;
        ${labels.totalHizb}: <strong>${(totalHizb || 0).toFixed(2)}</strong> ${labels.hizb}
      </div>
    </div>` : ''}

    <div class="section">
      <div class="section-header">${labels.memoReport}</div>
      <table>
        <thead>
          <tr>
            <th>${labels.date}</th>
            <th>${labels.surah}</th>
            <th>${labels.ayahs}</th>
            <th>${labels.evaluation}</th>
          </tr>
        </thead>
        <tbody>
          ${(records || []).map(r => {
            const from = r.fromAyah;
            const to = r.toAyah;
            const count = to - from + 1;
            const range = isAr ? `${to} ← ${from}` : `${from} → ${to}`;
            return `
            <tr>
              <td>${r.date}</td>
              <td>${r.surahName || '—'}</td>
              <td>${range} <span style="color:#94a3b8;font-size:11px">(${count})</span></td>
              <td>${evalBadge(r.evaluation, lang)}</td>
            </tr>`;
          }).join('')}
        </tbody>
      </table>
    </div>
  `;

  openPrintWindow(body, title || labels.memoReport, lang);
};

// ─────────────────────────────────────────────
export const exportProgressReportPDF = ({
  child, attendanceStats, memoProgress,
  teacherNotes, classN, period, schoolName, country, region, teacherName,
}) => {
  const lang = getCurrentLang();
  const labels = L[lang] || L.en;
  const isAr = lang === 'ar';

  const childName = isAr
    ? (child?.nameAr || child?.name || '')
    : (child?.nameEn || child?.name || '');

  const schoolLine = [schoolName, country, region].filter(Boolean).join(' — ');

  const body = `
    <div class="info-box">
      <div class="main-name">${childName}</div>
      <div class="meta">
        ${labels.class}: ${classN || '—'} &nbsp;|&nbsp; ${labels.period}: ${period || '—'}
        ${teacherName ? `<br>${labels.teacher}: ${teacherName}` : ''}
        ${schoolLine ? `<br>${schoolLine}` : ''}
      </div>
    </div>

    ${attendanceStats ? `
    <div class="section">
      <div class="section-header">${labels.attendance}</div>
      <div class="stats-row">
        <div class="stat-card sc-blue">
          <div class="sv">${attendanceStats.total}</div>
          <div class="sl">${labels.total}</div>
        </div>
        <div class="stat-card sc-green">
          <div class="sv">${attendanceStats.present}</div>
          <div class="sl">${labels.present}</div>
        </div>
        <div class="stat-card sc-red">
          <div class="sv">${attendanceStats.absent}</div>
          <div class="sl">${labels.absent}</div>
        </div>
        <div class="stat-card ${attendanceStats.rate >= 80 ? 'sc-green' : 'sc-gold'}">
          <div class="sv">${attendanceStats.rate}%</div>
          <div class="sl">${labels.rate}</div>
        </div>
      </div>
    </div>` : ''}

    ${memoProgress !== undefined ? `
    <div class="section">
      <div class="section-header">${labels.progress}</div>
      <div class="hizb-box">
        <div class="hv">${(memoProgress || 0).toFixed(2)}</div>
        <div class="hl">${labels.hizb} / 60</div>
        <div class="prog-wrap" style="margin-top:10px">
          <div class="prog-track">
            <div class="prog-fill" style="width:${Math.min(((memoProgress || 0) / 60) * 100, 100).toFixed(1)}%;background:linear-gradient(90deg,#d97706,#fbbf24)"></div>
          </div>
          <span style="font-size:12px;color:#92400e;white-space:nowrap">
            ${(((memoProgress || 0) / 60) * 100).toFixed(1)}%
          </span>
        </div>
      </div>
    </div>` : ''}

    ${teacherNotes ? `
    <div class="section">
      <div class="section-header">${labels.notes}</div>
      <div class="notes-box">${teacherNotes}</div>
    </div>` : ''}
  `;

  openPrintWindow(body, labels.progressReport, lang);
};

// ─────────────────────────────────────────────
export const exportAdminReportPDF = ({ period, classReports, rankingData }) => {
  const lang = getCurrentLang();
  const labels = L[lang] || L.en;
  const isAr = lang === 'ar';

  const body = `
    ${classReports?.length ? `
    <div class="section">
      <div class="section-header">${labels.classPerf}</div>
      <table>
        <thead>
          <tr>
            <th>${labels.class}</th>
            <th>${labels.teacher}</th>
            <th>${labels.students}</th>
            <th>${labels.rate}</th>
            <th>${labels.hizb}</th>
          </tr>
        </thead>
        <tbody>
          ${classReports.map(r => `
          <tr>
            <td><strong>${r.className}</strong></td>
            <td>${isAr ? (r.teacherAr || r.teacher) : (r.teacherEn || r.teacher)}</td>
            <td>${r.students}</td>
            <td>
              <span class="badge ${r.attendance >= 80 ? 'bg' : r.attendance >= 60 ? 'bo' : 'br'}">
                ${r.attendance}%
              </span>
            </td>
            <td>${(r.hizbProgress || 0).toFixed(2)}</td>
          </tr>`).join('')}
        </tbody>
      </table>
    </div>` : ''}

    ${rankingData?.length ? `
    <div class="section">
      <div class="section-header">${labels.studentRank}</div>
      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>${labels.name}</th>
            <th>${labels.class}</th>
            <th>${labels.hizb}</th>
            <th>${labels.rate}</th>
          </tr>
        </thead>
        <tbody>
          ${rankingData.slice(0, 10).map((s, i) => `
          <tr>
            <td>
              <span class="badge ${i === 0 ? 'bo' : i === 1 ? 'bb' : 'bp'}">#${i + 1}</span>
            </td>
            <td>${isAr ? (s.nameAr || s.name) : (s.nameEn || s.name)}</td>
            <td>${s.className || '—'}</td>
            <td><strong style="color:#b45309">${(s.hizbProgress || 0).toFixed(2)}</strong></td>
            <td>${s.attendance || 0}%</td>
          </tr>`).join('')}
        </tbody>
      </table>
    </div>` : ''}
  `;

  openPrintWindow(body, `${labels.schoolReport}${period ? ' — ' + period : ''}`, lang);
};
