import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatGregorian, formatHijri } from './hijriDate';

const BRAND_GREEN = [22, 163, 74];
const BRAND_GOLD = [245, 158, 11];
const TEXT_DARK = [15, 23, 42];
const TEXT_GRAY = [100, 116, 139];

const addHeader = (doc, title, subtitle = '') => {
  // Green header bar
  doc.setFillColor(...BRAND_GREEN);
  doc.rect(0, 0, 210, 28, 'F');

  // Gold accent line
  doc.setFillColor(...BRAND_GOLD);
  doc.rect(0, 28, 210, 3, 'F');

  // App name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Tatabu', 14, 16);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Quranic School Management', 14, 23);

  // Title on right
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 196, 14, { align: 'right' });

  if (subtitle) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle, 196, 22, { align: 'right' });
  }

  return 38;
};

const addFooter = (doc, pageNum, totalPages) => {
  const now = new Date();
  doc.setFontSize(8);
  doc.setTextColor(...TEXT_GRAY);
  doc.text(
    `Generated by Tatabu on ${formatGregorian(now)} | ${formatHijri(now)}`,
    14, 290
  );
  doc.text(`Page ${pageNum} of ${totalPages}`, 196, 290, { align: 'right' });
};

export const exportAttendancePDF = ({ title, studentName, classN, period, records, stats, lang = 'en' }) => {
  const doc = new jsPDF();
  let y = addHeader(doc, title || 'Attendance Report', `${classN || ''} — ${period || ''}`);

  // Student info box
  if (studentName) {
    doc.setFillColor(240, 253, 244);
    doc.roundedRect(14, y, 182, 18, 3, 3, 'F');
    doc.setTextColor(...TEXT_DARK);
    doc.setFontSize(10);
    doc.text(`Student: ${studentName}`, 20, y + 7);
    doc.text(`Period: ${period || ''}`, 20, y + 14);
    y += 24;
  }

  // Stats row
  if (stats) {
    const statBoxes = [
      { label: 'Total Sessions', value: stats.total },
      { label: 'Present', value: stats.present },
      { label: 'Absent', value: stats.absent },
      { label: 'Attendance Rate', value: `${stats.rate}%` },
    ];
    const boxW = 44;
    statBoxes.forEach((box, i) => {
      const x = 14 + i * (boxW + 2);
      doc.setFillColor(i % 2 === 0 ? 22 : 245, i % 2 === 0 ? 163 : 158, i % 2 === 0 ? 74 : 11);
      doc.roundedRect(x, y, boxW, 20, 2, 2, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(String(box.value), x + boxW / 2, y + 13, { align: 'center' });
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.text(box.label, x + boxW / 2, y + 19, { align: 'center' });
    });
    y += 28;
  }

  // Table
  const tableData = records.map(r => [
    r.date,
    r.hijriDate || '',
    r.studentName || '',
    r.status === 'present' ? '✓ Present' : '✗ Absent',
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Date', 'Hijri Date', 'Student', 'Status']],
    body: tableData,
    headStyles: { fillColor: BRAND_GREEN, textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [240, 253, 244] },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: {
      3: {
        fontStyle: 'bold',
        textColor: (cell) => cell.text[0]?.includes('Present') ? BRAND_GREEN : [220, 38, 38],
      },
    },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc, 1, 1);
  doc.save(`attendance_${Date.now()}.pdf`);
};

export const exportMemorizationPDF = ({ title, studentName, classN, records, totalHizb, lang = 'en' }) => {
  const doc = new jsPDF();
  let y = addHeader(doc, title || 'Memorization Report', classN || '');

  if (studentName) {
    doc.setFillColor(240, 253, 244);
    doc.roundedRect(14, y, 182, 18, 3, 3, 'F');
    doc.setTextColor(...TEXT_DARK);
    doc.setFontSize(10);
    doc.text(`Student: ${studentName}`, 20, y + 7);
    doc.text(`Total Progress: ${totalHizb?.toFixed(2) || 0} Hizb`, 20, y + 14);
    y += 24;
  }

  const tableData = records.map(r => [
    r.date,
    r.surahName || '',
    `${r.fromAyah} - ${r.toAyah}`,
    String(r.toAyah - r.fromAyah + 1),
    r.evaluation,
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Date', 'Surah', 'Ayahs Range', 'Count', 'Evaluation']],
    body: tableData,
    headStyles: { fillColor: BRAND_GREEN, textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [255, 251, 235] },
    styles: { fontSize: 9, cellPadding: 3 },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc, 1, 1);
  doc.save(`memorization_${Date.now()}.pdf`);
};

export const exportProgressReportPDF = ({ child, attendanceStats, memoProgress, teacherNotes, classN, period }) => {
  const doc = new jsPDF();
  let y = addHeader(doc, 'Progress Report', `${child?.name || ''} — ${period || ''}`);

  // Child info
  doc.setFillColor(240, 253, 244);
  doc.roundedRect(14, y, 182, 22, 3, 3, 'F');
  doc.setTextColor(...TEXT_DARK);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(child?.name || '', 20, y + 9);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Class: ${classN || 'N/A'}`, 20, y + 17);
  doc.text(`Period: ${period || ''}`, 100, y + 17);
  y += 28;

  // Attendance section
  doc.setTextColor(...BRAND_GREEN);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Attendance Summary', 14, y);
  y += 6;

  if (attendanceStats) {
    const cells = [
      { l: 'Total', v: attendanceStats.total },
      { l: 'Present', v: attendanceStats.present },
      { l: 'Absent', v: attendanceStats.absent },
      { l: 'Rate', v: `${attendanceStats.rate}%` },
    ];
    cells.forEach((c, i) => {
      const x = 14 + i * 46;
      doc.setFillColor(i < 2 ? 22 : 220, i < 2 ? 163 : 38, i < 2 ? 74 : 38);
      if (i === 3) doc.setFillColor(245, 158, 11);
      doc.roundedRect(x, y, 42, 16, 2, 2, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.text(String(c.v), x + 21, y + 11, { align: 'center' });
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.text(c.l, x + 21, y + 15.5, { align: 'center' });
    });
    y += 22;
  }

  // Memorization section
  doc.setTextColor(...BRAND_GOLD);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Memorization Progress', 14, y);
  y += 4;

  if (memoProgress !== undefined) {
    doc.setFillColor(255, 251, 235);
    doc.roundedRect(14, y, 182, 14, 2, 2, 'F');
    doc.setTextColor(...TEXT_DARK);
    doc.setFontSize(10);
    doc.text(`Total Hizb Memorized: ${memoProgress.toFixed(2)} / 60 Hizb`, 20, y + 9);
    y += 18;
  }

  // Teacher notes
  if (teacherNotes) {
    doc.setTextColor(...TEXT_DARK);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("Teacher's Monthly Notes", 14, y);
    y += 6;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...TEXT_GRAY);
    const lines = doc.splitTextToSize(teacherNotes, 180);
    doc.text(lines, 14, y);
    y += lines.length * 5 + 6;
  }

  addFooter(doc, 1, 1);
  doc.save(`progress_report_${Date.now()}.pdf`);
};

export const exportAdminReportPDF = ({ period, classReports, rankingData }) => {
  const doc = new jsPDF();
  let y = addHeader(doc, 'School Report', period || '');

  // Classes comparison
  doc.setTextColor(...BRAND_GREEN);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Class Performance Summary', 14, y);
  y += 6;

  if (classReports?.length) {
    const tableData = classReports.map(r => [
      r.className,
      r.teacher,
      String(r.students),
      `${r.attendance}%`,
      `${r.hizbProgress?.toFixed(2) || 0}`,
    ]);
    autoTable(doc, {
      startY: y,
      head: [['Class', 'Teacher', 'Students', 'Attendance', 'Hizb Avg']],
      body: tableData,
      headStyles: { fillColor: BRAND_GREEN, textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [240, 253, 244] },
      styles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 10;
  }

  // Student ranking
  if (rankingData?.length) {
    doc.setTextColor(...BRAND_GOLD);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Student Rankings', 14, y);
    y += 6;

    const rankData = rankingData.slice(0, 10).map((r, i) => [
      `#${i + 1}`,
      r.name,
      r.className || '',
      `${r.hizbProgress?.toFixed(2) || 0}`,
      `${r.attendance || 0}%`,
    ]);
    autoTable(doc, {
      startY: y,
      head: [['Rank', 'Student', 'Class', 'Hizb', 'Attendance']],
      body: rankData,
      headStyles: { fillColor: [245, 158, 11], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [255, 251, 235] },
      styles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
    });
  }

  addFooter(doc, 1, 1);
  doc.save(`school_report_${Date.now()}.pdf`);
};
